django_trace/urls.py
from django.urls import path
from django_trace.trace_views import AuditView, UsersAutocompleteView

app_name = "django_trace"

urlpatterns = [
    path('', AuditView.as_view(), name='audit'),
    path('users_autocompletion', UsersAutocompleteView.as_view(), name='users_autocompletion'),
]

django_trace/models.py
"""
This module defines the data model
"""
from django.db import models
from django.contrib.auth.models import User

from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.dispatch import receiver
from django.conf import settings

AUDIT = True
MAX_LEN = 300

if hasattr(settings, 'DJANGO_TRACE'):
    AUDIT = settings.DJANGO_TRACE.get('AUDIT', True)

if AUDIT:
    @receiver(user_logged_in)
    def login_callback(sender, **kwargs):
        """ trigged when the user logs in """
        user = User.objects.get(username=kwargs['user'].username)
        Audit.objects.create(user=user, action=Audit.LOGGED_IN)

    @receiver(user_logged_out)
    def logout_callback(sender, **kwargs):
        """ trigged when the user logs out """
        user = User.objects.get(username=kwargs['user'].username)
        Audit.objects.create(user=user, action=Audit.LOGGED_OUT)


class Audit(models.Model):
    """ captures any log-in/out activities """
    user = models.ForeignKey(User, null=True, blank=True,\
        on_delete=models.PROTECT)
    date = models.DateTimeField(auto_now=True)
    LOGGED_IN = 0
    LOGGED_OUT = 1
    ACTION_TYPES = [
        (LOGGED_IN, 'Logged in'),
        (LOGGED_OUT, 'Logged out')]
    action = models.PositiveIntegerField(choices=ACTION_TYPES)

    def __unicode__(self):
        act = 'Logged in'
        if self.action == self.LOGGED_OUT:
            act = 'Logged out'

        return u'{} {}'.format(self.user.username, act)


class Log(models.Model):
    """ captures any http requests sent """
    user = models.ForeignKey(User, null=True,\
        blank=True, on_delete=models.PROTECT)
    method = models.CharField(max_length=10)
    path = models.TextField()
    host = models.CharField(max_length=MAX_LEN)
    session = models.CharField(max_length=MAX_LEN,\
        null=True, blank=True)
    start = models.DateTimeField()
    info = models.TextField(null=True, blank=True)
    duration = models.FloatField()
    status = models.PositiveIntegerField()

    def __unicode__(self):
        return str(self.start)

django_trace/controller.py
from .models import Log
from django.core.paginator import Paginator
from datetime import datetime
from django.contrib.auth.models import User


def get_data(request):
    filter_session = request.GET.get('filter_session', '')
    filter_user = request.GET.get('filter_user', '')
    filter_user_name = ''
    filter_date_from = request.GET.get('filter_date_from', '')
    filter_date_to = request.GET.get('filter_date_to', '')
    queryset = Log.objects.all()
    if filter_session:
        queryset = queryset.filter(session=filter_session)

    if filter_user:
        queryset = queryset.filter(user=filter_user)
        filter_user_name = User.objects.filter(id=filter_user)[0].username

    if filter_date_from:
        naive_datetime = datetime.strptime(filter_date_from, '%Y-%m-%dT%H:%M')
        queryset = queryset.filter(start__gte=naive_datetime)
    
    if filter_date_to:
        naive_datetime = datetime.strptime(filter_date_to, '%Y-%m-%dT%H:%M')
        queryset = queryset.filter(start__lte=naive_datetime)
    
    queryset = queryset.order_by('-start')
    paginator = Paginator(queryset, 10)  # 10 items per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'filter_user': filter_user,
        'filter_user_name': filter_user_name,
        'logs': page_obj.object_list,
        'page_obj': page_obj,
    }
    return context

django_trace/templates/audit.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/forms.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/widgets.css' %}">
	<script src="{% static 'django_trace/jquery-3.7.1.min.js' %}"></script>
	<link href="{% static 'django_trace/select2.min.css' %}" rel="stylesheet">
	<script src="{% static 'django_trace/select2.min.js' %}"></script>
	<script src="{% static 'django_trace/audit.js' %}?v=3"></script>
</head>
<body>
	<form method="get" action="{% url 'django_trace:audit' %}">
		<div class="filters">
			<label for="filter-user">User:</label>
			<select id="filter-user" name="filter_user" data-placeholder="User" style="width: 200px;">
				{% if filter_user %}
				<option value="{{ filter_user }}" selected="selected">{{ filter_user_name }}</option>
				{% endif %}
			</select>
			
			<label for="filter-session">Session:</label>
			<input type="text" id="filter-session" name="filter_session" value="{{ request.GET.filter_session|default:'' }}" placeholder="Enter session id">

			<label for="filter-date-from">After:</label>
			<input type="datetime-local" id="filter-date-from" name="filter_date_from" value="{{ request.GET.filter_date_from|default:'' }}">

			<label for="filter-date-to">Before:</label>
			<input type="datetime-local" id="filter-date-to" name="filter_date_to" value="{{ request.GET.filter_date_to|default:'' }}">

			<button class="btn btn-primary" type="submit">Apply Filters</button>
		</div>
	</form>
	
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Timestamp</th>
                <th>User</th>
                <th>Method</th>
				<th>Duration</th>
				<th>Status</th>
				<th>Info</th>
				<th>Session</th>
				<th>path</th>
            </tr>
        </thead>
        <tbody>
            {% for log in logs %}
			<tr>
            <td>{{ log.start }}</td>
            <td>{{ log.user }}</td>
			<td>{{ log.method }}</td>
			<td>{{ log.duration }}</td>
			<td>{{ log.status }}</td>
			<td>{{ log.info }}</td>
			<td><a href="{% url 'django_trace:audit' %}?filter_session={{ log.session }}">{{ log.session }}</a></td>
			<td>{{ log.path }}</td>
			</tr>
			{% endfor %}
        </tbody>
    </table>
	
	<div class="pagination">
		<span class="step-links">
			{% if page_obj.has_previous %}
				<a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page=1">&laquo; first</a>
				<a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.previous_page_number }}">previous</a>
			{% endif %}

			<span class="current">
				Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			</span>

			{% if page_obj.has_next %}
				<a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.next_page_number }}">next</a>
				<a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.paginator.num_pages }}">&raquo; last</a>
			{% endif %}
		</span>
	</div>
</body>
</html>

django_trace/templates/audit_with_base.html
{% extends "base.html" %}
{% load static %}
{% block extra_head %}
<script src="{% static 'django_trace/jquery-3.7.1.min.js' %}"></script>
<link href="{% static 'django_trace/select2.min.css' %}" rel="stylesheet">
<script src="{% static 'django_trace/select2.min.js' %}"></script>
<script src="{% static 'django_trace/audit.js' %}?v=3"></script>
{% endblock %}

{% block content %}
<h1>Audit Logs</h1>
{% load static %}
	<form method="get" action="{% url 'django_trace:audit' %}">
		<div class="filters">
			<label for="filter-user">User:</label>
			<select id="filter-user" name="filter_user" data-placeholder="User" style="width: 200px;">
				{% if filter_user %}
				<option value="{{ filter_user }}" selected="selected">{{ filter_user_name }}</option>
				{% endif %}
			</select>
			
			<label for="filter-session">Session:</label>
			<input type="text" id="filter-session" name="filter_session" value="{{ request.GET.filter_session|default:'' }}" placeholder="Enter session id">

			<label for="filter-date-from">After:</label>
			<input type="datetime-local" id="filter-date-from" name="filter_date_from" value="{{ request.GET.filter_date_from|default:'' }}">

			<label for="filter-date-to">Before:</label>
			<input type="datetime-local" id="filter-date-to" name="filter_date_to" value="{{ request.GET.filter_date_to|default:'' }}">

			<button class="btn btn-primary" type="submit">Apply Filters</button>
		</div>
	</form>

    <table class="table table-striped">
        <thead>
            <tr>
                <th class="timestamp">Timestamp</th>
                <th>User</th>
                <th>Method</th>
				<th>Duration</th>
				<th>Status</th>
				<th>Info</th>
				<th>Session</th>
				<th>path</th>
            </tr>
        </thead>
        <tbody>
            {% for log in logs %}
			<tr>
            <td class="timestamp">{{ log.start }}</td>
            <td>{{ log.user }}</td>
			<td>{{ log.method }}</td>
			<td>{{ log.duration }}</td>
			<td>{{ log.status }}</td>
			<td>{{ log.info }}</td>
			<td><a href="{% url 'django_trace:audit' %}?filter_session={{ log.session }}">{{ log.session }}</a></td>
			<td>{{ log.path }}</td>
			</tr>
			{% endfor %}
        </tbody>
    </table>

	<div class="pagination">
		<span class="step-links">
			{% if page_obj.has_previous %}
				<a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page=1">&laquo; first</a>
				<a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.previous_page_number }}">previous</a>
			{% endif %}

			<span class="current">
				Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
			</span>

			{% if page_obj.has_next %}
				<a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.next_page_number }}">next</a>
				<a href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.paginator.num_pages }}">&raquo; last</a>
			{% endif %}
		</span>
	</div>
{% endblock %}